#!/bin/sh

worbli  push action eosio addproducer "{\"producer\":\"argentinaeos\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"beyondbtc1\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"bitfishrocks\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"blocksmithio\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"caleos\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"chainrift\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"dune1\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"eoscafeblock\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"eoscannonbp1\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"eosdac\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"eosiodetroit\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"eosdublin1\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"eosgermanyx1\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"eosiosg11111\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"eosmetal\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"eosnairobi\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"eosnationftw\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"eosnewyorkio\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"eosphere\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"eosrealbpc11\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"eosriobprod1\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"eossweden\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"eostitanprod\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"eostribewbi1\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"genereos\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"gravitypool1\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"hkeostestbp1\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"infinityblk1\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"octagonlabs\"}" -p eosio
worbli  push action eosio addproducer "{\"producer\":\"eosyskoreab1\"}" -p worbli.admin
worbli  push action eosio addproducer "{\"producer\":\"eosyskoreab2\"}" -p worbli.admin
worbli  push action eosio addproducer "{\"producer\":\"eosyskoreab3\"}" -p worbli.admin
worbli  push action eosio addproducer "{\"producer\":\"atticlabwrb1\"}" -p worbli.admin
worblim  push action eosio addproducer "{\"producer\":\"tokenika4wbl\"}" -p worbli.admin